### ISSUE TITLE
AssertionError when closing issue with existing labels

### ISSUE THREAD

**Issue by eburgueno** [bstriner/github-bot-close-inactive-issues#5]
Running this against one of our repositories, I am getting the following Traceback:

```
Traceback (most recent call last):
  File "<path>/bin/github-close-inactive-issues", line 11, in <module>
    load_entry_point('github-bot-close-inactive-issues==0.0.4', 'console_scripts', 'github-close-inactive-issues')()
  File "<path>/lib/python2.7/site-packages/github_bot_close_inactive_issues-0.0.4-py2.7.egg/github_bot_close_inactive_issues/close_inactive_issues.py", line 97, in main
    process_issues(config)
  File "<path>/lib/python2.7/site-packages/github_bot_close_inactive_issues-0.0.4-py2.7.egg/github_bot_close_inactive_issues/close_inactive_issues.py", line 46, in process_issues
    issue_close(issue, config, days_inactive, config["label"])
  File "<path>/lib/python2.7/site-packages/github_bot_close_inactive_issues-0.0.4-py2.7.egg/github_bot_close_inactive_issues/issues.py", line 37, in issue_close
    issue.edit(state='closed', labels=[labels])
  File "<path>/lib/python2.7/site-packages/PyGithub-1.34-py2.7.egg/github/Issue.py", line 307, in edit
    assert labels is github.GithubObject.NotSet or all(isinstance(element, (str, unicode)) for element in labels), labels
AssertionError: [Label(name="label1"), Label(name="label2"), Label(name="label3")]
```

All three labels are pre-existing (ie: I am not adding a new one upon closing using the `--label` option).

**Comment by mistercrunch** [comment]
+1 hit the same problem and used the same workaround, thanks @eburgueno
